# Generated by Django 3.1.2 on 2021-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicFavs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
